version: '3'
services: 
  user-api:
    build: .
    links:
      - mongo:mongo
    environment:
      - MONGO_ENPOINT=mongo:27017
      - MONGO_DB=irol
    ports:
      - "8080:8080"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/irol:/data/db